# Generated by Django 4.2.30 on 2026-06-04 07:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
