# Generated by Django 4.2.30 on 2026-06-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_todo_due_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("api_key", models.CharField(blank=True, default="", max_length=512)),
                ("base_url", models.URLField(default="https://api.openai.com/v1")),
                ("model", models.CharField(default="gpt-4o-mini", max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Settings",
                "verbose_name_plural": "AI Settings",
            },
        ),
    ]
